baseURL = 'https://blog.chum-bucket.site/'
languageCode = 'zh-cn'
DefaultContentLanguage = "zh"
title = '王司徒学术笔记'
theme = "diary"
enableLaTeX = true
enableGitalk = true
enableAutoDarkMode=true
enableReadingTime=true


[params]
cloudflareToken = "your cloudflare web analytics token"
googleAnalytics = "UA-123-45"
googleSiteVerification = "xxxx-xxxx"
googleSearchCode = "Your Search Code"
favicon = "assets/who.svg"

[params.gitalk]
  owner = "jiashun-wang"
  repo = "gitalk-comments"
  client_id = "Ov23liAVMdlJvffgysgp"
  client_secret = "f0a8af80b29c430e42bf6d3f58fdc8c4f1bd4858"



[markup.goldmark.renderer]
    unsafe = true


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# Menu configuration
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 1

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/archive"
name = "Archive"
weight = 3

[[menu.main]]
url = "/about"
name = "About"
weight = 98

[[menu.main]]
url = "/index.xml"
name = "RSS"
weight = 99

[taxonomies]
   category = "categories"
   tag = "tags"